### ISSUE TITLE
Закомментированый код

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#1]
Комментарии в коде нужны для обьяснения участка кода, но лучше не оставлять сам код в комментариях
Это можно делать в процессе разработки, но лучше не оставлять при коммите. Иначе появляется плохая привычка которая плохо влияет на чистоту кода

**Comment by winfar3** [comment]
Removed commented out code

**Comment by winfar3** [comment]
Moved the components <CategoriesItem/>, <Menu/>, <GalleryItem/>, <SocialItem/>, <TagsItem/> to a separate file
