### ISSUE TITLE
push

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#10]
```
  const pageNumbers = [];
  for (let i = 1; i <= props.maxPageNumber; i++) {
    pageNumbers.push(i);
  }
```
Попробуй сделать аналогичный код, но без функции `push`. Хорошая практика иммутабельности
Если что - пиши, дам подсказку :)

**Comment by DmitriiMelnikOnix** [comment]
Хороший вариант, можно пользоваться

Теперь еще чуть сложнее
Попробуй заменит `for` на `map` - теперь это практика функционального программирования)

**Comment by winfar3** [comment]
Заменил на 
```
let tempArray = new Array(props.maxPageNumber).fill(0);
  const pageNumbers = tempArray.map((item, pos) => {
    return ++pos;
  });
```
но мне кажется с этим вариантом что-то не так.

**Comment by DmitriiMelnikOnix** [comment]
На самом деле очень близко, но это можно записать в одну строку)
```
const pageNumbers = [...new Array(props.maxPageNumber)].map((item, pos) => pos + 1)
```
