### ISSUE TITLE
Падает при запуске

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#11]
Старайся чтобы при каждом коммите у тебя было рабочее приложение

Я так понимаю ты переделал структуру, но некоторые импорты остались старые
При импорте страниц `Main`, `Recipes` и `NotFoundPage` в `App.js` они ссылаются на папку `components` хотя компоненты уже находятся в `pages`. Похожая ситуация в `Main.js`

**Comment by winfar3** [comment]
Я при прошлом коммите не делал билд, собирался сделать еще правки и потом собрать все вместе. Извиняюсь
