### ISSUE TITLE
sortByDate

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#12]
```
 const sortByDate = () => {
    postCardData.sort(byField('date'));
    setPostCardData([...postCardData]); 
  }
```

В данном примере проблем быть не должно, но лучше избежать изменения стейта вне `setPostCardData` 
Сейчас получается что функция `sort` изменяет значение в стейте. Это аналогия `this.state.value = 42` 

Что-то вроде такого `const newArray =  [...oldArray].sort(...);` будет более правильно

**Comment by winfar3** [comment]
Изменил на 
```
const sortByDate = () => {
    const temp = [...postCardData].sort(byField('date'));
    setPostCardData([...temp]); 
  }
```
