### ISSUE TITLE
Удаление элемента из обьекта

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#14]
```
delete postCardData[pos].imageUrl;
setPostCardData([...postCardData]);
```

Обожаю такие пример, вроде мелочь, но вот что может из-за этого произойти и как может вылезти. В задании так и задумывалось использование `delete`, и по сути ты все сделал правильно и у тебя все работает

Ты удалил элемент из обьекта который находится в массиве
`[...postCardData]` - копирует только массив, а все обьекты и массивы внутри копируются по ссылке. В таком случае ты можешь делать с новым массивом что угодно и это никак не отобразится на исходном массиве, НО обьекты внутри по сути общие

```
const test = [{id: 1}, {id: 2}];
const test2= [...test];
test2[0].id = 3;
console.log(test)
console.log(test2)
```
Вот простой пример

А теперь то как это может повлиять, при использовании оптимизаций вы виде `PureComponent` или `React.memo` (я писал о них в чате) при рендере массива `postCardData` компонент в который ты передаешь данные может увидеть что это тот же обьект и не запускать перерендер и вроде как изображения в обьекте нет, но оно может не удалиться

Опять же, это просто предостережение и у тебя все хорошо работает. Но теперь ты знаешь что может быть и что искать)

Удалять элементы из обьекта можно так же через spread оператор, тогда создается новый обьект

**Comment by DmitriiMelnikOnix** [comment]
И по поводу твоего комментария. Как раз в этом случае с удалением изображения это именно тот случай где можно обновить обьект с помощью spread оператора. 
Или же еще один вариант, добавить редактирование комментариев или названия поста, или еще чего-то в таком роде

**Comment by winfar3** [comment]
Заменил 
```
delete postCardData[pos].imageUrl;
setPostCardData([...postCardData]);
```
на 
```
postCardData[pos] = {...postCardData[pos], imageUrl: null}
setPostCardData([...postCardData]);
```
Я правильно понял, что можно было сделать так?

**Comment by DmitriiMelnikOnix** [comment]
Можно еще по другому
```
const {imageUrl, otherData} = postCardData[pos]
```

После такого в `otherData` больше не будет поля imageURL

**Comment by winfar3** [comment]
С этим не разобрался? Можно подробнее или ссылку на какую-нибудь статью?

**Comment by winfar3** [comment]
Понял, спасибо
