### ISSUE TITLE
document.querySelector(".postcard_active");

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#27]
В React так лучше не делать. И как я писал раньше `document` лучше не использовать
Но если тебе нужно получить элемент чтобы проскролить к нему можно воспользоваться `ref`
https://ru.reactjs.org/docs/refs-and-the-dom.html

Но на данный момент это задача со звездочкой или даже двумя)

**Comment by winfar3** [comment]
Не уверен в правильности реализованного мной решения, потому что передаю ref через 3 компонента по пропсах, но работает. Подскажи, насколько правильно/неправильно, и как можно улучшить.
