### ISSUE TITLE
Адаптив в react компонентах

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#4]
Мы не будем проходить это на прямую но это заденет одну из будущих тем

```
 {(window.innerWidth > 767 && <HeaderNav/>)}
```

Адаптив через `window.innerWidth` лучше не делать. Это связано тем как работают компоненты
Компоненты по умолчанию перерендериваются когда:
- изменяется стейст
- изменються пропсы
- перерендеривается родительский компонент (по умолчанию но можно этого избежать)

А теперь к сути, при изменении размеров экрана компоненты не перерендериваются. Проблемой это может обернутся например на планшетах где одна сторона подходит под условие, а вторая нет. 

И то как это проявляется у тебя. Если открыть с маленьким расширением, а потом растянуть его, то  компонент `<HeaderNav/>` не появится.

PS: я видел что ты сделал и через css, этого будет достаточно

**Comment by winfar3** [comment]
Removed condition on window width for component <HeaderNav/> rendering
