### ISSUE TITLE
Еще больше расспаковки

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#43]
```
  const post = dataFromServer[0];
```
Строка из `Hero.js` 

А можно записать вот так 
```
  const [post] = dataFromServer;
```
Этот способ более предпочтительный

**Comment by winfar3** [comment]
https://github.com/winfar3/onix-internship/commit/7444d7a6574903dd3e46fcb871c00586825f4b5e
