### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#47]
Одна из причин по которой я советовал другой пример Layout в том что ним намного проще управлять. И не нужно привязываться в url как в твоем случае
` const isHomepage = useLocation().pathname === '/onix-internship/';`

В примере https://onixacademy.slack.com/archives/C0342N2U00H/p1653296271623779 можно изменять layout по логике из компонент через пропсы

**Comment by winfar3** [comment]
https://github.com/winfar3/onix-internship/commit/7d41a1490a029ffee91cee0098df6d33982e4518
