### ISSUE TITLE
функция в setState

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [winfar3/onix-internship#8]
```
onClick={() => setMenuActive(!menuActive)} 
```

Если новое значение стейта зависит от старого, нужно использовать функцию в качестве значения для setState
Получится что-то вроде такого
```
onClick={() => setMenuActive((oldMenuActive) => !oldMenuActive)}
```

**Comment by winfar3** [comment]
Почему так? И не до конца понял, oldMenuActive это переменная хранящая значение menuActive?

**Comment by winfar3** [comment]
Все, во время сегодняшнего урока понял, почему так
